### ISSUE TITLE
(한상수) 겜프프로젝트 과정평가용(방문기록)

### ISSUE THREAD

**Issue by GGMinwok** [hso2560/Repository525#1]
5/26 깃허브 접속확인

**Comment by GGMinwok** [comment]
오늘 기록할 때 지금까지 한 것(오늘 이전꺼~), 6/8 오늘 1-3교시에 한 것 구분해서 과정 기록 해주기!

**Comment by GGMinwok** [comment]
6/8 작업내용... issue등록된 것 확인함.

**Comment by hso2560** [comment]
6/15 작업내용
1 교시 : NavMesh에 대한 설명
2 교시 : NavMeshAgent에 대한 설명과 관련된 알면 좋은 추가 내용 
3 교시 : Tilemap 시스템에 대해서 정리

**Comment by GGMinwok** [comment]
6/22 이전주 작업상황 확인함

**Comment by hso2560** [comment]
6/22 작업내용
1 교시 : 유니티 주요 클래스 설명
2 교시 : 코루틴 설명 및 간단 예시
3 교시 : 지금까지의 내용 점검 및 수정

**Comment by GGMinwok** [comment]
고생했어요~^^
마지막 확인완료
작업과정 기록 남겨두세요. 
(2022년 동안 삭제 금지)
