### ISSUE TITLE
6/8 작업 내용 

### ISSUE THREAD

**Issue by hso2560** [hso2560/Repository525#2]
Mesh Renderer와 MeshFilter 컴포넌트에 대한 간단 설명(1교시), AudioSource컴포넌트에 대한 설명과 심플 사용방법 추가(1-2교시), Particle System에 대한 설명과 생명주기함수 (Start, Update 등)에 대한 설명과 실행 순서(2-3교시), EventTrigger컴포넌트 설명 추가(3교시)

**Comment by GGMinwok** [comment]
issue 따로 등록이 아니라 선생님이 만든 Issue에 comment 해주면 되오!!
